### ISSUE TITLE
useLink does not work in strict mode; useTitle does work ok

### ISSUE THREAD

**Issue by kompot** [0no-co/hoofd#69]
https://codesandbox.io/s/lucid-marco-fqsqtj?file=/src/App.js

If you disable `StrictMode` in `index.js` then `useLink` starts working as it should. Has no effect on `useTitle`

**Comment by JoviDeCroock** [comment]
That is a good point, `<link>` is a bit of a tough one as it allows for duplicates to be present hence we aren't doing very strict checks on them. The main reason behind this happening is that React executes effects twice. We actually try to find the node in the tree by matching all the attributes but we aren't finding it as the dom has not committed the paint yet 😅 I'm having to think pretty hard about this one tbh
